/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoSkillRouteImport } from './routes/$owner/$repo/$skill'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoSkillRoute = OwnerRepoSkillRouteImport.update({
  id: '/$owner/$repo/$skill',
  path: '/$owner/$repo/$skill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/$skill': typeof OwnerRepoSkillRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/$skill': typeof OwnerRepoSkillRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/$skill': typeof OwnerRepoSkillRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/submit'
    | '/$owner'
    | '/$owner/$repo/$skill'
    | '/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submit' | '/$owner' | '/$owner/$repo/$skill' | '/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/submit'
    | '/$owner/'
    | '/$owner/$repo/$skill'
    | '/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubmitRoute: typeof SubmitRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerRepoSkillRoute: typeof OwnerRepoSkillRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$skill': {
      id: '/$owner/$repo/$skill'
      path: '/$owner/$repo/$skill'
      fullPath: '/$owner/$repo/$skill'
      preLoaderRoute: typeof OwnerRepoSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmitRoute: SubmitRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerRepoSkillRoute: OwnerRepoSkillRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
